import { expandGlob } from "@std/fs/expand-glob";
import { createParser } from "deno-tree-sitter";
import sql from "common-tree-sitter-languages/sql.js";

if (import.meta.main) {
  const parser = await createParser(sql);
  for await (const entry of expandGlob("**/*.sql")) {
    console.log(entry.path);

    const sourceCode = await Deno.readTextFile(entry.path);
    const ast = parser.parse(sourceCode);
    console.log(ast);

    const result =
      "// This file was generated by sql-embedder. Do not edit manually.\n\n" +
      JSON.stringify(ast, null, 2);

    const outPath = entry.path.replace(/(\.sql)$/, ".sql.ts");
    await Deno.writeTextFile(outPath, result);
  }
}
