import { expandGlob } from "@std/fs/expand-glob";
import { default as nsp } from "node-sql-parser";

if (import.meta.main) {
  for await (const entry of expandGlob("**/*.sql")) {
    const parser = new nsp.Parser();
    const sourceCode = await Deno.readTextFile(entry.path);
    const ast = parser.astify(sourceCode);
    console.log(ast);

    const result =
      "// This file was generated by sql-embedder. Do not edit manually.\n\n";
    const outPath = entry.path.replace(/(\.sql)$/, ".sql.ts");
    await Deno.writeTextFile(outPath, result);
  }
}
