import { expandGlob } from "@std/fs/expand-glob";
import { createParser } from "deno-tree-sitter";
import sql from "common-tree-sitter-languages/sql.js";

// TODO: Generate input and output interfaces for each statement.

if (import.meta.main) {
  const parser = await createParser(sql);
  for await (const entry of expandGlob("**/*.sql")) {
    console.log(entry.path);

    const sourceCode = await Deno.readTextFile(entry.path);
    const ast = parser.parse(sourceCode);
    if (!ast) {
      throw new Error("Failed to parse SQL file: " + entry.path);
    }

    // Extract statements and preceding comments
    const statements: { statement: string; comments: string[] }[] = [];
    let pendingComments: string[] = [];

    for (const child of ast.rootNode.children) {
      if (child.type === "comment") {
        pendingComments.push(child.text);
      } else if (child.type === "statement") {
        statements.push({
          statement: child.text,
          comments: pendingComments,
        });
        pendingComments = [];
      } else {
        // Ignore whitespace and other nodes
      }
    }

    const seen = new Set<string>();
    let result =
      "// This file was generated by sql-embedder. Do not edit manually.\n\n";

    for (const statement of statements) {
      const variableName = statement.comments
        .at(0)
        ?.match(/^--\s+(\w+)(\s|$)/)
        ?.at(1);
      if (!variableName) {
        console.warn(
          "Failed to extract variable name from statement. Skipping",
          statement,
        );
        continue;
      }

      if (seen.has(variableName)) {
        console.warn("Duplicate variable name: " + variableName);
        continue;
      }

      result += `/**\n`;
      for (const comment of statement.comments) {
        result += ` * ${comment.replace(/^--\s+/, "")}\n`;
      }
      result += ` */\n`;

      result += `export const ${variableName} = ${
        JSON.stringify(statement.statement)
      };\n\n`;
      seen.add(variableName);
    }

    const outPath = entry.path.replace(/(\.sql)$/, ".sql.ts");
    await Deno.writeTextFile(outPath, result);
  }
}
