import { assertEquals } from "@std/assert";
import { embedSql, parseSql } from "./sql-embedder.ts";

Deno.test("parseSql parses single statement with comment", () => {
  const sql = `-- myQuery
SELECT 1;`;
  const results = parseSql(sql);
  assertEquals(results.length, 1);
  assertEquals(results[0].comments, ["-- myQuery"]);
  assertEquals(results[0].sql, "SELECT 1;");
});

Deno.test("parseSql parses multiple statements with comments", () => {
  const sql = `-- query1
SELECT 1;

-- query2 (description)
SELECT 2;`;
  const results = parseSql(sql);
  assertEquals(results.length, 2);
  assertEquals(results[0].comments, ["-- query1"]);
  assertEquals(results[0].sql, "SELECT 1;");
  assertEquals(results[1].comments, ["-- query2 (description)"]);
  assertEquals(results[1].sql, "SELECT 2;");
});

Deno.test("parseSql handles statements without comments", () => {
  const sql = `SELECT 1;
-- query2
SELECT 2;`;
  const results = parseSql(sql);
  assertEquals(results.length, 2);
  assertEquals(results[0].comments, []);
  assertEquals(results[0].sql, "SELECT 1;");
  assertEquals(results[1].comments, ["-- query2"]);
  assertEquals(results[1].sql, "SELECT 2;");
});

Deno.test("parseSql handles multi-line CREATE TRIGGER statements", () => {
  const sql = `-- trigger1
CREATE TRIGGER t1
AFTER INSERT ON foo
BEGIN
  SELECT 1;
END;

-- query1
DELETE FROM foo WHERE id = ?;`;

  const results = parseSql(sql);
  assertEquals(results.length, 2);
  assertEquals(results[0].comments, ["-- trigger1"]);
  assertEquals(results[0].sql.includes("CREATE TRIGGER"), true);
  assertEquals(results[0].sql.includes("END;"), true);
  assertEquals(results[1].comments, ["-- query1"]);
  assertEquals(results[1].sql, "DELETE FROM foo WHERE id = ?;");
});

Deno.test("parseSql handles multiple CREATE TRIGGER statements", () => {
  const sql = `-- trigger1
CREATE TRIGGER t1
AFTER INSERT ON foo
BEGIN
  SELECT 1;
END;

-- trigger2
CREATE TRIGGER t2
AFTER DELETE ON foo
BEGIN
  SELECT 2;
END;

-- query1
SELECT * FROM foo;`;

  const results = parseSql(sql);
  assertEquals(results.length, 3);
  assertEquals(results[0].comments, ["-- trigger1"]);
  assertEquals(results[1].comments, ["-- trigger2"]);
  assertEquals(results[2].comments, ["-- query1"]);
});

Deno.test("embedSql generates valid typescript", () => {
  const sql = `-- query1
SELECT 1;`;
  const result = embedSql(sql);
  const expected =
    `// This file was generated by sql-embedder. Do not edit manually.

/**
 * query1
 */
export const query1 = "SELECT 1;";

`;
  assertEquals(result, expected);
});

Deno.test("embedSql handles multiple queries and multiline descriptions", () => {
  const sql = `-- query1
-- Description line 1
-- Description line 2
SELECT 1;

-- query2
SELECT 2;`;
  const result = embedSql(sql);
  const expected =
    `// This file was generated by sql-embedder. Do not edit manually.

/**
 * query1
 * Description line 1
 * Description line 2
 */
export const query1 = "SELECT 1;";

/**
 * query2
 */
export const query2 = "SELECT 2;";

`;
  assertEquals(result, expected);
});

Deno.test("embedSql warns and skips statements without valid variable name", () => {
  const sql = `SELECT 1;`;
  // We can't easily check console.warn here, but we can check that it returns empty except for header
  const result = embedSql(sql);
  const expected =
    `// This file was generated by sql-embedder. Do not edit manually.\n\n`;
  assertEquals(result, expected);
});
