/**
 * embedSql generates a TypeScript module string from SQL source code.
 */
export function embedSql(sourceCode: string): string {
  const statements = parseSql(sourceCode);

  const seen = new Set<string>();
  let result =
    "// This file was generated by sql-embedder. Do not edit manually.\n\n";

  for (const statement of statements) {
    // Variable name from first (topmost) comment.
    const variableName = statement.comments
      .at(0)
      ?.match(/^--\s+(\w+)(\s|$)/)
      ?.at(1);
    // Format: -- variableName (description optional)
    if (!variableName) {
      console.warn(
        `No valid preceding comment for statement. Add "-- variableName" (description optional). Skipping.`,
        statement,
      );
      continue;
    }

    if (seen.has(variableName)) {
      console.warn("Duplicate variable name: " + variableName);
      continue;
    }

    result += `/**\n`;
    for (const comment of statement.comments) {
      result += ` * ${comment.replace(/^--\s+/, "")}\n`;
    }
    result += ` */\n`;

    result += `export const ${variableName} = ${
      JSON.stringify(statement.sql)
    };\n\n`;
    seen.add(variableName);
  }

  return result;
}

/**
 * ParsedSqlStatement represents a single parsed SQL statement.
 */
export interface ParsedSqlStatement {
  comments: string[];
  sql: string;
}

/**
 * parseSql parses SQL source code and returns an array of parsed SQL statements.
 *
 * This function uses a simple line-by-line approach:
 * - Lines starting with "--" are treated as comments
 * - Comments mark the beginning of a new SQL statement
 * - All non-comment lines between comment blocks are grouped as SQL
 *
 * This approach is dialect-agnostic and works with any SQL syntax,
 * including complex constructs like CREATE TRIGGER, CTEs, etc.
 */
export function parseSql(sourceCode: string): ParsedSqlStatement[] {
  const results: ParsedSqlStatement[] = [];
  const lines = sourceCode.split("\n");

  let currentComments: string[] = [];
  let currentSql: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith("--")) {
      // Found a comment line
      if (currentSql.length > 0) {
        // Save the previous statement
        results.push({
          sql: currentSql.join("\n").trim(),
          comments: currentComments,
        });
        currentSql = [];
        currentComments = [];
      }
      currentComments.push(line);
    } else if (trimmed.length > 0) {
      // SQL content
      currentSql.push(line);
    } else if (currentSql.length > 0) {
      // Empty line - keep it as part of current SQL
      currentSql.push(line);
    }
  }

  // Don't forget the last statement
  if (currentSql.length > 0) {
    results.push({
      sql: currentSql.join("\n").trim(),
      comments: currentComments,
    });
  }

  return results;
}
