// This file was generated by sql-embedder. Do not edit manually.

/**
 * authorsTable creates the authors table.
 */
export const authorsTable =
  "CREATE TABLE authors (\r\n  id BIGINT PRIMARY KEY,\r\n  name text NOT NULL,\r\n  bio text\r\n)";

/**
 * getAuthor gets an author by id.
 */
export const getAuthor =
  "SELECT\r\n  *\r\nFROM\r\n  authors\r\nWHERE\r\n  id = ?\r\nLIMIT\r\n  1";

/**
 * listAuthors lists all authors.
 */
export const listAuthors =
  "SELECT\r\n  *\r\nFROM\r\n  authors\r\nORDER BY\r\n  name";

/**
 * createAuthor creates a new author.
 */
export const createAuthor =
  "INSERT INTO\r\n  authors (name, bio)\r\nVALUES\r\n  (?, ?)\r\nRETURNING\r\n  *";

/**
 * updateAuthor updates an author by id.
 */
export const updateAuthor =
  "UPDATE\r\n  authors\r\nSET\r\n  name = ?,\r\n  bio = ?\r\nWHERE\r\n  id = ?";

/**
 * deleteAuthor deletes an author by id.
 */
export const deleteAuthor = "DELETE FROM\r\n  authors\r\nWHERE\r\n  id = ?";
